springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  server:
    port: 8081

aegis:
  seed-enabled: false
  failure-simulation-enabled: false
  cookie-secure: true
  redis:
    enabled: true
